### ISSUE TITLE
Using Bincrafters Qt instead of yours

### ISSUE THREAD

**Issue by ShamanTcler** [kenfred/conan-qwt#1]
First let me thank you for your work, and I don't mean it insult you work.

I am trying to use Bincrafters  (https://bincrafters.github.io/) Qt instead of yours (Qt/5.8.0@kenfred/testing).  

Specifically Qt 5.9.7 LTS (long term support) for MSVS 2015

I  have attached the conanfile.py (as .txt) below.

My changes were:
1) build_requires = "Qt/5.9.7@bincrafters/stable"      (available from "bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]" )

2) then I changed "svg" to "qtsvg" as qtsvg is a bincrafters Qt option.

3) added a few print statements because I am still learning

I have attached the files below. The build.txt
[build.txt](https://github.com/kenfred/conan-qwt/files/2590388/build.txt)
[conanfile.txt](https://github.com/kenfred/conan-qwt/files/2590393/conanfile.txt)

build.txt is a capture of:

conan create . test_package/example

and terminates with:

ERROR: Qwt/6.1.3@test_package/example: Error in build() method, line 75
        self._build_msvc()
while calling '_build_msvc', line 102
        self.run("cd qwt-%s && %s && qmake -r qwt.pro" % (self.version, vcvars))
        ConanException: Error 3 while executing cd qwt-6.1.3 && echo Conan:vcvars already set && qmake -r qwt.pro

Any guidance would be appreciated.

BTW ... 

- Qt 5.12 LTS should be available in 2 months and I will likely move to it also. 
- Also looking at layering QXsls into the same Qt with Conan

**Comment by kenfred** [comment]
Hi @ShamanTcler.

The `svg` option is for this recipe for the QWT package and doesn't have an impact on the QT recipe. Are you doing this simply for consistent naming? Should be fine.

```
self.run("cd qwt-%s && %s && qmake -r qwt.pro" % (self.version, vcvars))
        ConanException: Error 3 while executing cd qwt-6.1.3 && echo Conan:vcvars already set && qmake -r qwt.pro
```

It fails because of the `echo Conan:vcvars already set`. That is not what `vcvars` should expand to, so the command is invalid.

Your issue is probably related to [this thread](https://github.com/conan-io/conan/issues/1733#issuecomment-328307753):
>That error happens when you are already running in an environment or command prompt from another compiler version. We couldn't find information that activating a "vcvars" environment over an existing one was clean, so in order to activate an environment via "vcvars", no previous environment has to be set. So in your error message, you are running in a VS15 environment (prompt, or previousely set via vcvars) and trying to activate VS14 via vcvars.

Good luck!

**Comment by ShamanTcler** [comment]
Thanks for the reply.

The Bincrafters build sets the option QtSvg. With QtSvg set to false I believe Svg is left out of the Qt build. They have a list of about 15-20 Qt options. Guess I will deal with that dragon when I get to it.... when it starts to compile.

The VCVARS issue. I thought that is what you were trying to do. For mine I will strip it out for now. I am trying to EVENTUALLY work out a docker build. With that there will be one and only one compiler suite (MSVS C/Intel FORTRAN) installed. For now it is one compiler suite per machine.

The idea is to layer the following:

      Qwt       QXlsx (https://github.com/j2doll/QXlsx)        Qtcsv (https://github.com/iamantony/qtcsv)
           \                             |                                                   /
                            Qt (https://github.com/bincrafters/conan-qt)

Are there any other libs layered on top of Qt that might be of interest?

Well as the saying goes ..."Once more unto the breach"

**Comment by kenfred** [comment]
@ShamanTcler The `svg` option is only for the QWT recipe. It does nothing for the QT recipe. Renaming to `qtsvg` doesn't change that.

To affect the options in a dependency recipe, you need to scope it with the dependency name [as described here](https://docs.conan.io/en/latest/mastering/conanfile_py.html).

So you could have both at the same time:
`default_options = {"svg": True, "Qt:qtsvg": True}`

The first one is setting the default option for the current package (QWT in this case) and the second one is setting an option on the dependency. **They are completely independent**.

As for vcvars, you can't strip it out. It needs to be there to source the visual studio environment and find the build tools. Your issue is the shell you're in has already sourced a different visual studio environment from the options defined by your build configuration. Solution: do the conan build from a clean shell (either CMD, PowerShell, or Git Bash) and NOT from the visual studio command prompt.

**Comment by ShamanTcler** [comment]
Back again ... got it working for me. So what I have working is:
Win 10 64
MSVS 2015
Conan 1.9
CMake
Qt 5.9.7 (Bincrafters) 
Qwt 6.1.3

Two examples from qwt compiled with CMake  scatter & oscilloscope.

At this stage I am pretty confident it works so on to the other libs.

I used your recipe as a start, so I have two questions.

1) Do you want copies of what I have done?

2) Would you mind if I shared the work with Bincrafters? I figured my work is simply a derivative so I would  be polite to ask first.

Regards
Carl

**Comment by kenfred** [comment]
Hey Carl. Yes, I'd be interested in any improvements you've made. Feel free to share with Bincrafters.

Thanks,
Ken

**Comment by ShamanTcler** [comment]
Still a work in progress but here is what I have...the new version is a bit chatty, but I am still learning Python.

Give me a good C/C++/FORTRAN compiler and I am fine.... :)

Note: for now the designer option is set to False .... it gives the build heartburn 

And the file is really conanfile.py, not conanfile.txt ....so the uploader will take it
[conanfile.txt](https://github.com/kenfred/conan-qwt/files/2620586/conanfile.txt)

**Comment by kenfred** [comment]
thanks, if you'd like to contribute, please submit a pull request.
